[package]
name = "domain"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
uuid.workspace = true
thiserror.workspace = true
strum.workspace = true
strum_macros.workspace = true
utoipa.workspace = true